# Generated by Django 3.0.2 on 2020-01-30 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.FloatField()),
                ('incident_state', models.FloatField()),
                ('resolved_at', models.FloatField()),
                ('opened_at', models.FloatField()),
                ('number', models.FloatField()),
                ('sys_mod_count', models.FloatField()),
                ('u_priority_confirmation', models.FloatField()),
                ('duree', models.FloatField(null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
